### ISSUE TITLE
Undefined domain in verification email

### ISSUE THREAD

**Issue by neatglyphs** [krgamestudios/kingdombattles#13]
I used the sign up form at https://kingdombattles.net/signup and received a verification email.
However the email was sent from `signup@undefined` 

The domain name part of the URL was also set as undefined in the verification link.
Basically the email I got looked like this:

```
Hello! Please visit the following address to verify your account: http://undefined/verifyrequest?email=[MY-EMAIL]&verify=[MY-VERIFICATION-TOKEN]
```

Still managed to verify my account by using the query params with the kingdombattles.net-domain

**Comment by Ratstail91** [comment]
Problem resolved - I forgot the environment variables when dockerizing this program.
